clear,clc;
w = warning ('off','MATLAB:MKDIR:DirectoryExists');

movieNames = {'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00001.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00004.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00010.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00021.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00031.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00057.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00078.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00340.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00351.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00710.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00734.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00795.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00882.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00066.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00684.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00239.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00242.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00300.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00308.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00438.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00463.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00484.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00491.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00546.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00553.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00598.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00626.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00629.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00763.avi'};

tic;
sal = ImageSaliency;
for i = 1:size(movieNames,2)
    fileName = movieNames{i}
    regexres = regexp(fileName,'.avi','split');
    if ~exist([regexres{1} '\ImprovedTrajectoryOriginalTJS.mat'], 'file')
        saliencyMap = sal.Cigdem(fileName);
    end
    toc;
end
    
    