clear,clc;

movieNames = {'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00001.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00004.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00010.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00031.avi',...
            'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00084.avi'};
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00057.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00078.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00340.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00351.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00710.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00734.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00795.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptest00882.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00039.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00057.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00066.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00073.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00088.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain0094.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00121.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00135.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00134.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00141.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00172.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00218.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00234.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00239.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00240.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00242.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00300.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00308.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00438.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00463.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00484.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00491.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00546.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00553.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00598.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00626.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00629.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00681.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00684.avi',...
%             'F:\Thesis\Hollywood2-actions\Hollywood2\AVIClips\actioncliptrain00763.avi'};
methodName = 'Itti';

tic;
sal = ImageSaliency;
for i = 1:size(movieNames,2)
    
    video = VideoReader(movieNames{i});
    frames = read(video);
    
    switch methodName
        case 'Judd'
            saliencyMap = sal.MyJudd(movieNames{i},frames);
        case 'ImpTrj'
            if exist([movieNames{i} '_impTrajectories.mat'], 'file') == 2
                load([movieNames{i} '_impTrajectories.mat']);
                saliencyMap = sal.ImpTrj(movieNames{i},frames,impTrajectories);
            end     
        case 'AITE'
            saliencyMap = sal.ActionsInTheEyeFixation(movieNames{i},frames,video.Duration);
        case 'Itti'
            saliencyMap = sal.MyItti(movieNames{i},frames);
        otherwise
            disp('No such saliency algoritm!')
    end
    
    if exist('saliencyMap','var')
        save([movieNames{i} '_' methodName '_Saliency.mat'],'saliencyMap');
    end
    toc;
end








